name: Deploy static site to GitHub Pages

on:
  push:
    branches: [main]  # or "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload website files
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .  # or path: ./dist if your files are in a build folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
